services:
  mpd:
    image: wernight/mopidy:latest
    ports:
      - "6600:6600"
      - "6680:6680"
    user: "105:100"
    volumes:
      - "/run/user/$UID/pulse:/run/user/105/pulse"
      - "./mopidy-data/media:/var/lib/mopidy/media:ro"
      - "./mopidy-data/local:/var/lib/mopidy/local"
      - "./mopidy-data/playlists:/var/lib/mopidy/playlists"
    restart: unless-stopped
  web:
    image: shinsenter/phpfpm-nginx:php8-alpine
    environment:
      APP_UID: "$UID"
      APP_GID: "100"
    links:
      - mopidy
    ports:
      - "7080:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
