services:
  mopidy:
    image: wernight/mopidy:latest
    ports:
      - "6600:6600"
      - "6680:6680"
    user: "105:100"
    volumes:
      - "/run/user/$UID/pulse:/run/user/105/pulse"
      - "$PWD/media:/var/lib/mopidy/media:ro"
      - "$PWD/local:/var/lib/mopidy/local"
  web:
    image: shinsenter/phpfpm-nginx:php8-alpine
    environment:
      APP_UID: "$UID"
      APP_GID: "100"
    links:
      - mopidy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .:/var/www/html
